# Generated by Django 6.0.5 on 2026-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена курса в рублях",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
